### ISSUE TITLE
clearer handling of  `data_path` on creation 

### ISSUE THREAD

**Issue by cmdoret** [sdsc-ordes/modos-api#58]
Currently, we use `data-file` on the CLI, and the yaml file uses `data_path` as the source path for files to add into the modo.
This is unclear for the user because:
1. we don't differentiate (semantically) between source and target during the copy/upload operation
2. argument name is very similar to the schema property but means something else

**Objective:** clearly separate the path inside the object from the source path  when importing.

**Requirements:**
+ [ ] better cli parameter name: `--source-file`
+ [ ] yaml should clearly isolate schema properties from arguments
  + currently we use some hacks in the backend to replace values when loading yaml

**Proposal:**
Instead of having a list of elements with unique `id`s, we have a list of objects with `metadata` and `args` keys:
```yaml
# before
- id: abc
  name: A B C
  data_path: /data/source.xyz
```
```yaml
# after
- metadata:
    id: abc
    name: A B C
  args:
    source_file: /data/source.xyz
```
