### ISSUE TITLE
[Feature request]: infer `data_path`

### ISSUE THREAD

**Issue by cmdoret** [sdsc-ordes/modos-api#85]
### Description

when including data files in a modo, one must specify both source_file and data_path. This is redundant as most often, data_path is just the filename of source_file.

### Importance Level

Low

### Affected Components

api, cli

### Technical Requirements

infer data_path as filename(source_file) by default

### Acceptance criteria

users can leave data_path empty

**Comment by cmdoret** [comment]
set_data_path should probably be called from `modos.api._add_any_element` instead of [`modos.api.from_file`](https://github.com/sdsc-ordes/modos-api/blob/0d39cb14b21e5dabc628674558e0e8e0fdfa8e1a/modos/api.py#L537)

**Comment by almutlue** [comment]
My mistake - now I remember why we only use `set_data_path` in [modos.api.from_file](https://github.com/sdsc-ordes/modos-api/blob/0d39cb14b21e5dabc628674558e0e8e0fdfa8e1a/modos/api.py#L537):

`modos.api._add_any_element` accepts an element of type `modos_schema.datamodel.DataEntity` as input and in `modos_schema` `data_path` is a required field, so element generation will fail, if `data_path` it not specified in advance. It is the same issue we had before, e.g. when discussing auto generating `creation_date`.

I checked it again, and I think we could still solve this by using LinkML defaults (see [ifabsent](https://linkml.io/linkml/schemas/slots.html#default-values)) instead of inferring them in `modos.api`. I'm not sure if it is desirable though, because it further couples api and schema?

Another problem is that `ifabsent` does not support dynamic assignment based on the value of another slot. So we would still need to process the default in modos.api, which makes the solution dirty/hacky e.g.:

In `linkml yaml`:
```yaml
data_path:
    description: >-
      The path to access a resource, on a network or local filesystem.
      Can be a path relative to the root of the digital object, a URL,
      or an absolute path.
    range: string
    required: true
    ifabsent: "NEEDS_DEFAULT"
```

In `modos.api`:
```python
if element.get("data_path") == "NEEDS_DEFAULT":
    element["data_path"] = set_data_path(element, args.get("source_file"))
```
What is your opinion @cmdoret ?
